async function main() {}

main.then(() => process.exit(0)).catch((error) => {
    console.log
});